### PR TITLE
Update citizen.md

### PR DESCRIPTION
**Pull request by venomousbirds**

### CODE REVIEW

**Comment by McTsts** [comment]
Good addition to the role!

**Comment by Mjnstag** [comment]
notes are always good!

**Comment by venomousbirds** [comment]
comment. aaa.

**Comment by McTsts** [comment]
I made T uppercase

**Comment by venomousbirds** [comment]
I saw. don't think it should be uppercase

**Comment by Mjnstag** [comment]
good enough for me

**Pull request merged**
